### ISSUE TITLE
Implement a test framework using JUnit

### ISSUE THREAD

**Issue by dagansandler** [sagioto/forum#12]
Needs to include:
-Test template for Server side testing
-Test template for Client side testing

**Comment by sagioto** [comment]
by the way, take notice i used a maven plugin that runs the tests concurrently so the server test should assume they run together.
or remove this if it's a problem

**Comment by dagansandler** [comment]
Runs the tests concurrently?

Please elaborate.
How does the whole maven-building-testing thingy works? What's the general process that happens and when.

**Comment by sagioto** [comment]
view the pom https://github.com/sagioto/forum/blob/master/ForumServer/pom.xml
notice the maven-surefire-plugin can run 10 test methods concurrently
every time you issue mvn package all the tests under the test folders (either beginning or ending with Test) will run at the same time, this saves, actually if each test uses it's own reference nothing can go wrong else, it is best the the tests will use login data the includes the Test class name, and we a also check for multiple clients

**Comment by dagansandler** [comment]
This is not needed anymore.
