### ISSUE TITLE
Fix ServerNetworkAdaptor

### ISSUE THREAD

**Issue by dorleitman** [sagioto/forum#17]
After 2 hours trying to committing my work, the compiler yelled at me that on ServerNetworkAdaptor issues:
1. Forced me to add these:
   public bool EditPost(string postToUpdate, string originalPost, string usrname, string password)
         {
             throw new NotImplementedException();
         }
   
   ```
     public bool RemovePost(string postkey, string username, string password)
     {
         throw new NotImplementedException();
     }
   ```
2. Forced me to remove username fields from the following methods:
   public bool EditPost(string postToUpdate, string originalPost, string password)
       {
           Postkey originalPostKey = serializer.DeserializePostkey(originalPost);
           Post toUpdate = serializer.DeserializePost(postToUpdate);
           return controller.EditPost(originalPostKey, toUpdate, originalPostKey.Username, password);
       }
   
   ```
   public bool RemovePost(string postkey, string password)
   {
       Postkey originalPostKey = serializer.DeserializePostkey(postkey);
       return controller.RemovePost(originalPostKey, originalPostKey.Username , password);
   }
   ```

i updated the call to remove/edit post with  originalPostKey.Username.

I dont know why he did it, I just tried to make it work.
Sorry if i messed up your code. Please check, update & restore if needed (at least now the solution runs)

**Comment by sagioto** [comment]
since the code compiled when i committed it i fail to see it as my responsibility.
by looking at the commits section you can browse to an earlier version of the code and change to like in here: 
https://github.com/sagioto/forum/blob/0e8f5366911edca32214e4bf246713ad6aabdcc5/ForumServer/ServerController.cs
and change to it(i'm not sure it's latest))
