### ISSUE TITLE
Server interface redundancy - Enter & GetSubforumsList

### ISSUE THREAD

**Issue by dagansandler** [sagioto/forum#18]
Enter() and GetSubforumsList() are essentially the same, also being implemented the exact same way by the Server Network Adapter.

Is there a future consideration behind it? If not, maybe they should be merged.

**Comment by sagioto** [comment]
yes, enter is used for historical reasons can be dropped

**Comment by dagansandler** [comment]
seeing that this is the first iteration on C#, this should either be
removed from the contract or marked as deprecated.
as soon as that's done, this issue can be closed.
On May 11, 2012 9:19 PM, "Sagi Bernstein" <
reply@reply.github.com>
wrote:
