### ISSUE TITLE
ServerUtils namespaces

### ISSUE THREAD

**Issue by dagansandler** [sagioto/forum#19]
The Serializer and the shared datatypes (Subforum, Post, etc) have moved to ServerUtils but are still using the namespace ForumServer.

This causes Client dependency on the Server rather than on the Utils.

**Comment by sagioto** [comment]
i don't get it, did you fix it already?
if so please close, if not, all commits should be on a code with no compilation errors so please revert and fix

**Comment by dagansandler** [comment]
I didn't fix this yet. However, code still compiles correctly.

I changed the serializer's namespace, but not the datatypes.  This needs
some more thought and work and therefore stays as it is for the moment.
If you have any suggestions, please share them.
On May 11, 2012 9:17 PM, "Sagi Bernstein" <
reply@reply.github.com>
wrote:

**Comment by sagioto** [comment]
why not remove them from server make sever depend on utils and change the
includes in the server code

On Fri, May 11, 2012 at 9:34 PM, Dagan Sandler <
reply@reply.github.com

**Comment by dorleitman** [comment]
Agree. This is what should be done.
You guys want me to do it?

Sagi - did you test your code? I predict a crash tomorrow night/Sunday morning when we will try all the components together...

**Comment by dagansandler** [comment]
that's the general idea and they are already in Utils but with the old
namespace.
anyway, they are not Utils and should be given a dedicated namespace
On May 11, 2012 9:36 PM, "Sagi Bernstein" <
reply@reply.github.com>
wrote:

**Comment by dorleitman** [comment]
Fixed. Namespace is ForumUtils.SharedDataTypes. 
Dont have energy for thinking about new namespace for that...
Code is compiling & running.
