### ISSUE TITLE
Serialization of type Subforum fails

### ISSUE THREAD

**Issue by dagansandler** [sagioto/forum#20]
An ArgumentException is thrown with the message: Recursion Limit Exceeded.

This is most probably due to a circle inside of the object.

In order to recreate the bug:
1. Start the server and load some data into it (you can use the Init... method in the data manager)
2. Call  serializer.Serialize with controller.Enter() as argument.
3. Exception is thrown.

**Comment by sagioto** [comment]
Try to delete the recursion line from the serializer
On May 12, 2012 1:13 AM, "Dagan Sandler" <
reply@reply.github.com>
wrote:

**Comment by dagansandler** [comment]
That's not the issue...

**Comment by dagansandler** [comment]
Turns out that was PART of the problem. Without the recursion limit (that was set to 1) we get the following:

Type 'System.Collections.Generic.Dictionary`2[[ForumUtils.SharedDataTypes.Postkey, ForumUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null],[ForumUtils.SharedDataTypes.Post, ForumUtils, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' is not supported for serialization/deserialization of a dictionary, keys must be strings or objects.

**Comment by sagioto** [comment]
The json serialization is just an optimization over the soap one, we can
not use it and send the objects themselves (wcf will serialize), if
dictionary is still a problem we should send somthing else...
On May 12, 2012 1:33 AM, "Dagan Sandler" <
reply@reply.github.com>
wrote:

**Comment by sagioto** [comment]
okay, i'm gonna create new data types for client side, subforum is not needed as it is just the string name,
and client post will be with an array of clientreplies messages without the reply, also it will be an a sorted array, by order
it will also have a bool indicating if there are replies for the message

**Comment by sagioto** [comment]
another option is to make the replies non serializable

**Comment by sagioto** [comment]
dagan, i've inserted some changes, please look at the above commit comment
