### ISSUE TITLE
Registration of new users does not work

### ISSUE THREAD

**Issue by dagansandler** [sagioto/forum#21]
When calling the Register method on the server - an exception is thrown

Exception is thrown by data manager instead of returning null when the user does not exist.

**Comment by dorleitman** [comment]
I made it to raise an exception on purpose. Catch the exception into an error message to user.
Do you prefer me to return you NULL instead of an exception?

**Comment by dagansandler** [comment]
The exception is raised on the server side. It doesn't reach the client, which expects a true/false response on both Login & Register actions according to the Interface.

**Comment by dorleitman** [comment]
But how will the client know what was the problem? 
Wouldn't it be better if the client will get exceptions telling the reason of failure of actions? 
Sagi - please advice.

**Comment by dagansandler** [comment]
How can the **Client** catch exceptions that are thrown on the **Server**??

Specific responses can be possibly returned as int values to the client. But in order for that to happen, the Server must support it and then the interface can be updated accordingly.

**Comment by sagioto** [comment]
We can add to the service declartion for the operations to throw exceptions
On May 12, 2012 2:17 AM, "Dagan Sandler" <
reply@reply.github.com>
wrote:

**Comment by sagioto** [comment]
[FaultContract(typeof(Excption))]

or something similar

**Comment by dagansandler** [comment]
Yes, faults seem to be the way to go on these issues.

**HOWEVER**, the issue here is that registering a new user that does not exist should not generate a fault on the Client side. It should register a new user :)

**Comment by sagioto** [comment]
True, i guess tommorrow i'll declare faults on the whole service and write
tests
Possibly drop the whole json thing as it is not really needed but that
means changes to the service api
On May 12, 2012 2:27 AM, "Dagan Sandler" <
reply@reply.github.com>
wrote:

**Comment by sagioto** [comment]
assigned to dor as the fix is in the dataManager

**Comment by dorleitman** [comment]
What is it that  you want me to fix?
First of all you have to use AddUser(user) instead of UpdateUser(user) - User doesn't exists so it make sense that updateUser throws UserNotFoundExcpetion.
Secondly, would you like a method IsUserExists(user)? instead of calling GetUser(user) & get exception...

**Comment by sagioto** [comment]
Give me null if it doesn't exist
On May 12, 2012 10:13 AM, "dorleitman" <
reply@reply.github.com>
wrote:

**Comment by dorleitman** [comment]
Fixed. Issue is closed.
