### ISSUE TITLE
Connection to server doesn't work

### ISSUE THREAD

**Issue by dorleitman** [sagioto/forum#27]
Dagan, 
Does the connection to server works fine with the changes you made (on the fly connection)? 
Can you lets say, register from console without a problem?
I am not really sure why but i get some error messages from server. I think its about messages length & types between client to server. 

I tried it with the previous connection version & everything worked great,  when i update it with your new change it crashed...
I didnt want to touch it. So for now, at least for me, the connection doesnt work...
Please see if it works for you.

**Comment by sagioto** [comment]
according to what i've seen in the last few days connection works fine for both web and console

**Comment by dorleitman** [comment]
I will sit on it with dagan tomorrow... Go to sleep...
On May 30, 2012 4:12 AM, "Sagi Bernstein" <
reply@reply.github.com>
wrote:

**Comment by dorleitman** [comment]
FIXED. Things look different  in the morning...
