### ISSUE TITLE
Remove bug - fixed

### ISSUE THREAD

**Issue by dorleitman** [sagioto/forum#32]
The files are committed.

Sorry for all those changes, but i made another change in SQL table definition. Due to that you guys need to drop tblPostKey & create it again.

Commands needed:

/_drop old table_/
DROP TABLE dbo.tblPosts

/_Create updated table_/
USE [Forum]
GO

/*****\* Object:  Table [dbo].[tblPostKeys]    Script Date: 06/03/2012 01:29:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tblPostKeys]([PostKeyId] [int] NOT NULL,
    [Username] [nvarchar]%2850%29 NOT NULL,
    [Time] [datetime] NOT NULL,
 CONSTRAINT [PK_tblPostKey] PRIMARY KEY CLUSTERED 
%28
    [PostKeyId] ASC
%29WITH %28PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON%29 ON [PRIMARY]) ON [PRIMARY]

GO

ALTER TABLE [dbo].[tblPostKeys]  WITH CHECK ADD  CONSTRAINT [FK_tblPostKeys_tblUsers] FOREIGN KEY([Username])
REFERENCES [dbo].[tblUsers]([UserName])
GO

ALTER TABLE [dbo].[tblPostKeys] CHECK CONSTRAINT [FK_tblPostKeys_tblUsers]
GO

**Comment by sagioto** [comment]
close
